[book]
title = "MyLog - 我的经验与记录"
authors = ["BoringCat"]
description = "这里是我记录生活与工作中遇到或解决的一些难题"
language = "zh-cmn-Hans"
multilingual = false
src = "src"

[output.html]
default-theme = "Rust"
preferred-dark-theme = "Coal"
git-repository-url = "https://github.com/boringcat/Mygitbook"
git-repository-icon = "fa-github"
copy-fonts = false
no-section-label = true
additional-css = ["css/custom.css"]
input-404 = "哦吼.md"

[output.html.print]
enable = false    # include support for printable output
page-break = true # insert page-break after each chapter

[output.html.fold]
enable = true     # whether or not to enable section folding
level = 0         # the depth to start folding

[output.html.playground]
editable = false         # allows editing the source code
copyable = true          # include the copy button for copying code snippets
copy-js = true           # includes the JavaScript for the code editor
line-numbers = true      # displays line numbers for editable code
runnable = true          # displays a run button for rust code

